name: "Remove Unnecessary Files"
on:
    push:
      branches:
        - main
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
          - name: List folder contents
            run: ls -la
          - name: Remove .DS_Store File
            run: ./checks.sh

