name: "Remove Unnecessary Files"
on:
    push:
      branches:
        - main
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

    remove-ds-store:
        runs-on: ubuntu-latest
        steps:
          - name: Remove .DS_Store File
            run: pwd

